### ISSUE TITLE
Regarding the timeline for iOS 17 support

### ISSUE THREAD

**Issue by tonnetonne814** [mega6453/AppiumWizard#12]
I am personally very interested in this project.
I would like to ask a few questions about the development progress!

How long do you think it will take to support iOS 17 and later?
Is an Apple Developer Account absolutely necessary?

Thank you very much for your help.

**Comment by mega6453** [comment]
Appium Wizard is depends on go-iOS project for now. So if there is a release from go-iOS to support iOS 17, then I'll add it to the Appium Wizard ASAP.  If it's not , then I'm thinking to use pymobiledevice3 (which has iOS 17 support already). But the thing is, there is no direct windows exe or C# library for that. It developed using python. So, need to see how to integrate that with Appium Wizard project which is developed using C#. So, I don't have the date right now.

You need Mobile provision file and P12 file and it's password for running iOS automation. So yes, you will need Apple developer account for that.

**Comment by mega6453** [comment]
@tonnetonne814 Latest version (2.0.0) of Appium Wizard supports iOS version 17.4 and above.
